# Aqui vai ser um codigo com um lista com as funções do python para o aprendizado e vão ser dividd]idas em iniciante, intermediario e avanaçado

dificuldades = ["iniciante", "intermediario", "avancado"] # aqui é definido uma lista com as dificuldades
print('Escolha a dificuldade que deseja aprender:') #imprimi a mensagem que esta dentro das ''
print('1 - Iniciante \n2 - Intermediário \n3 - Avançado \n') #imprimi a mensagem que esta dentro das ''
dificuldade_escolhida = input('Digite o número da dificuldade: ') #aqui ele vai coletar o numero da dificuldade para a variavel dificuldade_escolhida
if dificuldade_escolhida == '1': # aqui ele verifica se a dificuldade escolhida é igual a 1, se for ele vai executar o bloco de código abaixo
    print('Agora vou apresentar as funçoes de python para o nivel iniciante') #imprimi a mensagem que esta dentro das ''
    print(' 1 - Variáveis\n  Variáveis são usadas para armazenar informações que podem ser usadas posteriormente no código. Elas são criadas atribuindo um valor a um nome de variável.\n  Ex. x = 10, nome = "João"') #imprimi a mensagem que esta dentro das ''
    print (' 2 - Imprimir mensagens na tela\n  Utilizamos a função print('') que vai imprimir a mensagem que está dentro das aspas\n  Ex. print("Olá, mundo!") = Olá, mundo!') #imprimi a mensagem que esta dentro das ''
    print(' 3 - Coletar informações do usuário\n  Utilizamos a função input() para coletar informações do usuário. O que estiver dentro dos parênteses será a mensagem que o usuário verá quando for solicitado a inserir uma informação.\n  Ex. nome = input("Digite seu nome: ")') #imprimi a mensagem que esta dentro das ''
    print(' 4 - Condicionais\n  As estruturas condicionais permitem que o código tome decisões com base em condições. A estrutura mais comum é o if, que executa um bloco de código se uma condição for verdadeira.\n  Ex. if x > 5:\n        print("x é maior que 5")') #imprimi a mensagem que esta dentro das ''
    print(' 5 - Loops\n  Os loops permitem que um bloco de código seja executado repetidamente enquanto uma condição for verdadeira. O loop mais comum é o while, que continua a executar o bloco de código enquanto a condição for verdadeira.\n  Ex. while x < 10:\n        print(x)\n        x += 1') #imprimi a mensagem que esta dentro das ''
elif dificuldade_escolhida == '2': # aqui ele verifica se a dificuldade escolhida é igual a 2, se for ele vai executar o bloco de código abaixo
    print('Agora vou apresentar as funçoes de python para o nivel intermediário') #imprimi a mensagem que esta dentro das ''
    print(' 1 - Listas\n  Listas são usadas para armazenar múltiplos itens em uma única variável. Elas são criadas usando colchetes [] e os itens são separados por vírgulas.\n  Ex. frutas = ["maçã", "banana", "laranja"]') #imprimi a mensagem que esta dentro das ''
    print(' 2 - Dicionários\n  Dicionários são usados para armazenar pares de chave-valor. Eles são criados usando chaves {} e os pares de chave-valor são separados por vírgulas.\n  Ex. pessoa = {"nome": "João", "idade": 30}') #imprimi a mensagem que esta dentro das ''
    print(' 3 - Funções\n  Funções são blocos de código reutilizáveis que realizam uma tarefa específica. Elas são definidas usando a palavra-chave def e podem receber parâmetros e retornar valores.\n  Ex. def saudacao(nome):\n        return f"Olá, {nome}!"') #imprimi a mensagem que esta dentro das ''
    print(' 4 - Módulos\n  Módulos são arquivos que contêm código Python que pode ser importado e usado em outros arquivos. Eles são criados usando a palavra-chave import e podem conter funções, classes e variáveis.\n  Ex. import math') #imprimi a mensagem que esta dentro das ''
    print(' 5 - Manipulação de arquivos\n  Python permite ler e escrever arquivos usando as funções open(), read(), write() e close(). Isso é útil para armazenar dados ou ler informações de arquivos existentes.\n  Ex. with open("arquivo.txt", "r") as arquivo:\n        conteudo = arquivo.read()') #imprimi a mensagem que esta dentro das ''
elif dificuldade_escolhida == '3': # aqui ele verifica se a dificuldade escolhida é igual a 3, se for ele vai executar o bloco de código abaixo
    print('Agora vou apresentar as funçoes de python para o nivel avançado') #imprimi a mensagem que esta dentro das ''
    print(' 1 - Programação orientada a objetos\n  A programação orientada a objetos é um paradigma de programação que utiliza objetos e classes para organizar o código. Ela permite criar estruturas de dados complexas e reutilizáveis.\n  Ex. class Pessoa:\n        def __init__(self, nome, idade):\n            self.nome = nome\n            self.idade = idade') #imprimi a mensagem que esta dentro das ''
    print(' 2 - Decoradores\n  Decoradores são funções que modificam o comportamento de outras funções. Eles são usados para adicionar funcionalidades extras a uma função sem modificar seu código original.\n  Ex. def decorador(funcao):\n        def wrapper():\n            print("Antes da função")\n            funcao()\n            print("Depois da função")\n        return wrapper') #imprimi a mensagem que esta dentro das ''
    print(' 3 - Geradores\n  Geradores são funções que retornam um iterador e permitem iterar sobre uma sequência de valores. Eles são criados usando a palavra-chave yield em vez de return.\n  Ex. def contador(n):\n        i = 0\n        while i < n:\n            yield i\n            i += 1') #imprimi a mensagem que esta dentro das ''
    print(' 4 - Expressões lambda\n  Expressões lambda são funções anônimas que podem ser usadas para criar funções simples e rápidas. Elas são criadas usando a palavra-chave lambda seguida por uma lista de parâmetros e uma expressão.\n  Ex. quadrado = lambda x: x**2') #imprimi a mensagem que esta dentro das ''
    print(' 5 - Manipulação avançada de arquivos\n  Python oferece recursos avançados para manipulação de arquivos, como leitura e escrita em formatos específicos (CSV, JSON), manipulação de arquivos binários e uso de bibliotecas como os.path para trabalhar com caminhos de arquivos.\n  Ex. import os\n     caminho = os.path.join("pasta", "arquivo.txt")') #imprimi a mensagem que esta dentro das '' 
else: # aqui ele verifica se a dificuldade escolhida é diferente de 1, 2 ou 3, se for ele vai executar o bloco de código abaixo
    print('Opção inválida. Por favor, escolha uma dificuldade válida.') #imprimi a mensagem que esta dentro das ''